export enum MediaCollectionType {
  USER = 'USER',
  COMPANY = 'COMPANY',
  BRAND = 'BRAND',
  LIFESTYLE = 'LIFESTYLE',
  AMENITY = 'AMENITY',
  RANKING_CATEGORY = 'RANKING_CATEGORY',
  RESIDENCE = 'RESIDENCE',
  RESIDENCE_UNIT = 'RESIDENCE_UNIT',
}
