export enum EmailTemplatesEnum {
  RESET_PASSWORD = 'reset-password',
  WELCOME = 'welcome',
  VERIFY_EMAIL = 'verify-email',
  INVITE = 'invite',
  FORGOT_PASSWORD = 'forgot-password',
  CLAIM_REQUEST = 'claim-request',
  CLAIM_REQUEST_APPROVED = 'claim-request-approved',
  CUSTOMER_REQUEST_REVIEW = 'customer-request-review',
  CUSTOMER_SUPPORT_ACKNOWLEDGMENT = 'customer-support-acknowledgment',
  INITAL = 'initial',
  JOB_APPLICATION = 'job-application',
  LOW_STAR_REVIEW = 'low-star-review',
  ON_FORM_SUBMIT = 'on-form-submit',
  REJECTED_CLAIM_REQUEST = 'rejected-claim-request',
  REQUEST_REVIEW = 'request-review',
  REVIEW_RESPONSE = 'review-response',
  REVIEW_WEEKLY_SUMMARY = 'review-weekly-summary',
  SPECIFIC_WORDS_REVIEW = 'specific-words-review',
}
